<?php
namespace evondu\metronic\field;

use yii\helpers\Html;
use evondu\metronic\SwitchAsset;

/*
<?= $form->field($model,"username")->bootstrapSwitch([
    "onColor"=>\metronic\field\BootstrapSwitch::CLASS_PRIMARY,
    "offColor"=>\metronic\field\BootstrapSwitch::CLASS_DEFAULT,
    "size"=>\metronic\field\BootstrapSwitch::SIZE_NORMAL,
    "readonly"=>false,
    "onText"=>"ON",
    "offText"=>"OFF"
])?>
 */
class BootstrapSwitch extends MetronicInputWidget
{
    public $onClass = self::CLASS_PRIMARY;
    public $offClass = self::CLASS_DEFAULT;
    public $size = self::SIZE_NORMAL;
    public $readonly = false;
    public $onText = "ON";
    public $offText = "OFF";

    public function run()
    {
        //Parent
        parent::run(); // TODO: Change the autogenerated stub

        //Load Assets
        SwitchAsset::register($this->view);

        //Options
        $options = [
            "class"=>"make-switch",
            "data-off-color"=>$this->offClass,
            "data-on-color"=>$this->onClass,
            "data-size"=>$this->size,
            "data-off-text"=>$this->offText,
            "data-on-text"=>$this->onText,
        ];
        if($this->value)
            $options["checked"] = "";
        if($this->readonly)
            $options["readonly"] = "";

        //Input
        $input = Html::input("checkbox",$this->name,$this->value,$options);

        //Output
        echo $input;
    }
}
?>