<?php
namespace metronic\field;

use metronic\widgets\TreeView;
use yii\helpers\Html;

/*
<?= $form->field($model, 'editAreas')->checkboxTree(
    //数据选项
    [
        [ "id" => "ajson1", "parent" => "#", "text" => "Simple root node" ,"data"=>"11" ,"icon"=>"fa fa-briefcase icon-state-success"],
        [ "id" => "ajson2", "parent" => "#", "text" => "Root node 2" ,"data"=>"12"],
        [ "id" => "ajson3", "parent" => "ajson1", "text" => "Child 1" ,"data"=>"13"],
        [ "id" => "ajson4", "parent" => "ajson1", "text" => "Child 2" ,"data"=>"14"],
    ],
    //配置信息
    [
        //选填，可以自动生成
        "id"=>"tree",
        //配置input的name属性
        "checkboxName"=>'tree',
        //是否为wholerow样式
        "wholerow" => false,
        //是否关联父级子级选择，即勾选父级自动勾选所有子级
        "threeState" => true,
        //是否选择后的显示背景颜色
        "keepSelectedStyle" => true,
    ])
?>
 */
class CheckboxTree extends MetronicInputWidget
{
    public $items = [];
    public $options = [];

    public function run()
    {
        //parent
        parent::run(); // TODO: Change the autogenerated stub
        
        //selected
        foreach ($this->items as $key=>$value){
            if(!empty($value["data"])){
                if(array_search($value["data"],$this->value) !== false){
                    if(!isset($this->items["state"]))
                        $this->items[$key]["state"] = array();
                    $this->items[$key]["state"]["selected"] = true;
                }
            }
        }

        //options
        $this->options["items"] = $this->items;
        $this->options["checkbox"] = true;
        $this->options["checkboxName"] = $this->name;
        $this->options["items"] = $this->items;

        //output
        echo TreeView::widget($this->options);
    }
}
?>