<?php
namespace evondu\metronic\field;

use evondu\metronic\widgets\SummernoteEditor;
use yii\helpers\Html;

/*
<?= $form->field($model, 'editAreas')->edit([
    //Summernote的配置
]) ?>
 */
class Editor extends MetronicInputWidget
{
    const TYPE_SUMMERNOTE = "summernote";

    public $type = self::TYPE_SUMMERNOTE;
    public $options = [];
    private $widgetId;

    public function init()
    {
        $this->widgetId = uniqid();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //parent
        parent::run(); // TODO: Change the autogenerated stub

        //options
        $this->options["id"] = $this->widgetId;
        $this->options["name"] = $this->name;
        $this->options["value"] = $this->value;

        //output
        switch ($this->type){
            case self::TYPE_SUMMERNOTE:
                echo SummernoteEditor::widget($this->options);
                break;
            default:
                ;
        }
    }
}
?>