<?php
namespace evondu\metronic\field;

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use evondu\metronic\DatePickerAsset;
use evondu\metronic\widgets\Button;

/*
<?= $form->field($model, 'photo')->other('common\widgets\fileinput\ImageInput', [
    //外部widgets的配置(已经隐含了models和attribute)
    'template'=>'{input}',
    'uploadPath'=>yii\helpers\Url::to(['/helpers/file/upload-base64']),
    'uploadType'=>'base64'
]) ?>
 */
class Other extends MetronicInputWidget
{
    /**
     * @var string
     */
    public $widget = "";
    public $options = [];

    /*
     * run
     */
    public function run()
    {
        //Parent
        parent::run(); // TODO: Change the autogenerated stub

        //Options
        $options = ArrayHelper::merge($this->options, ['model' => $this->model, 'attribute' => $this->attribute]);

        //Output
        echo ($this->widget)::widget($options);
    }
}
?>