<?php
namespace evondu\metronic\field;

use yii\helpers\Html;
use evondu\metronic\Select2Asset;

/*
<?= $form->field($model,"username")->select2(
    //下拉框的选项，支持二级
    [
        "CA"=>"California",
        "NV"=>"Nevada",
        "OR"=>"Oregon",
        "WA"=>"Washington",
        "Mountain Time Zone"=>[
            "AZ"=>"Arizona",
            "CO"=>"Colorado",
            "ID"=>"Idaho",
        ]
    ],
    //配置项
    [
        //是否多选
        "multiple" => false
    ]
)?>
 */
class Select2 extends MetronicInputWidget
{
    public $items = [];
    public $multiple = false;
    public $selectOptions = [];
    public $placeholder = "Select a State";

    public function run()
    {
        //Parent
        parent::run(); // TODO: Change the autogenerated stub

        //Load Assets
        Select2Asset::register($this->view);

        //Value
        $select = $this->renderSelect();

        //Output
        echo $select;
    }

    public function renderSelect(){
        //SelectOptions
        $this->selectOptions["id"] = $this->id;
        $this->selectOptions["name"] = $this->name;
        $this->selectOptions["data-placeholder"] = $this->placeholder;
        Html::addCssClass($this->selectOptions,'form-control select2-hidden-accessible');
        if($this->multiple){
            $this->selectOptions["multiple"]="";
            Html::addCssClass($this->selectOptions,'select2-multiple');
        }
        else
            Html::addCssClass($this->selectOptions,'select2');

        //Items
        $option[] = Html::tag("option","");
        foreach ($this->items as $key=>$value){
            $option[] = $this->renderItem($key,$value);
        }

        //Select
        $select = Html::tag("select",implode("\n",$option),$this->selectOptions);

        //Return
        return $select;
    }

    public function renderItem($key,$value){
        //是否为数组(optgroup)
        if(is_array($value) && !empty($value)){
            foreach ($value as $key2=>$value2){
                $option[] = $this->renderItem($key2,$value2);
            }
            $optgroup = Html::tag("optgroup",implode("\n",$option),["label"=>"$key"]);
            return $optgroup;
        }
        //不为数组(option)
        else{
            $options = ["value"=>$key];
            if($key == $this->value)
                $options["selected "]="";
            $option = Html::tag("option",$value,$options);
            return $option;
        }
    }
}
?>