<?php
namespace evondu\metronic\field;

use yii\helpers\Html;
use evondu\metronic\TagsInputAsset;

/*
<?= $form->field($model,"username")->tagsInput([])?>
 */
class TagsInput extends MetronicInputWidget
{
    public function run()
    {
        //Parent
        parent::run(); // TODO: Change the autogenerated stub

        //Load Assets
        TagsInputAsset::register($this->view);

        //Options
        $options = ["data-role"=>"tagsinput"];

        //Input
        $input = Html::input("text",$this->name,$this->value,$options);

        //Output
        echo $input;
    }
}
?>