<?php
namespace evondu\metronic\widgets;

use yii\helpers\Html;

/*
use metronic\widgets\Badge
<?= Badge::widget([
        'text'=>'SUCCESS',
        'class'=>Badge::TYPE_SUCCESS,
        'label'=>false,
        'round'=>false
    ])?>
 */
class Badge extends MetronicWidget
{
    //type
    const TYPE_INFO = "info";
    const TYPE_DANGER = "danger";
    const TYPE_DEFAULT = "default";
    const TYPE_PRIMARY = "primary";
    const TYPE_WARNING = "warning";
    const TYPE_SUCCESS = "success";
    //params
    public $text = '';
    public $type = self::TYPE_DEFAULT;
    public $label = false;
    public $round = false;

    /**
     * @return string
     */
    public function run(){
        parent::run(); // TODO: Change the autogenerated stub

        $type = $this->label?"label":"badge";
        $options = ['class'=>"$type",];
        Html::addCssClass($options,"$type-$this->type");

        if($this->label == false && $this->round == true)
            Html::addCssClass($options,"badge-roundless");

        $span = Html::tag("div",$this->text,$options);

        echo $span;
    }
}
?>