<?php
namespace evondu\metronic\widgets;

use yii\helpers\Html;

/*
use evondu\metronic\widgets\GridView
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'id',
        'name',
        ['class' => 'evondu\metronic\widgets\ActionColumn'],
    ],
]); ?>
 */
class GridView extends \yii\grid\GridView
{
    public $tableOptions = [
        'class'=>'table table-striped table-bordered table-hover'
    ];
    public $layout='
            <div class="table-scrollable">{items}</div>
            <div class="row">
                <div class="col-md-5 col-sm-5">{summary}</div>
                <div class="col-md-7 col-sm-7"><div class="dataTables_paginate paging_bootstrap_number">{pager}</div></div>
            </div>';
    public $pager=[
        'prevPageLabel'=>'<',
        'nextPageLabel'=>'>',
        //'firstPageLabel'=>"First",
        //'lastPageLabel'=>'Last',
        //'options'=>['class'=>'dataTables_paginate paging_bootstrap_full_number'],
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //附加Class
        Html::addCssClass($this->options,"dataTables_wrapper");
    }
}
?>