<?php
namespace evondu\metronic\widgets;

use yii\helpers\Html;

/*
use evondu\metronic\widgets\ProgressBar
<?= ProgressBar::widget([
    // 进度值：1-100
    'value'=>20,
    // 显示样式：
    // THEME_BASIC：默认样式
    // THEME_STRIPED：条纹样式
    // TYPE_ANIMATED：带动画条纹样式
    'theme'=>ProgressBar::TYPE_ANIMATED
    // 类型：info、danger、primary、success、warning
    'class'=>ProgressBar::CLASS_SUCCESS,
    // 是否显示文字进度
    'showText'=>true
    // 是否存在下部外边距
    'marginBottom'=>true
])?>
 */
class ProgressBar extends MetronicWidget
{
    //const
    const THEME_BASIC = "basic";
    const THEME_STRIPED = "striped";
    const THEME_ANIMATED = "animated";
    //type
    const TYPE_INFO = "info";
    const TYPE_DANGER = "danger";
    const TYPE_DEFAULT = "default";
    const TYPE_PRIMARY = "primary";
    const TYPE_WARNING = "warning";
    const TYPE_SUCCESS = "success";
    //params
    public $value = 50;
    public $theme = self::THEME_BASIC;
    public $type = self::CLASS_SUCCESS;
    public $showText = false;
    public $marginBottom = true;

    /**
     * @return string
     */
    public function run(){
        parent::run(); // TODO: Change the autogenerated stub

        $barOptions = [
            'class'=>'progress-bar',
            'role'=>'progressbar',
            'aria-valuenow'=>$this->value,
            'aria-valuemin'=>1,
            'aria-valuemax'=>100,
            'style'=>"width: $this->value%"
        ];
        Html::addCssClass($barOptions,"progress-bar-info");
        switch ($this->type){
            case self::TYPE_INFO:
                Html::addCssClass($barOptions,"progress-bar-info");
                break;
            case self::TYPE_WARNING:
                Html::addCssClass($barOptions,"progress-bar-warning");
                break;
            case self::TYPE_DANGER:
                Html::addCssClass($barOptions,"progress-bar-danger");
                break;
            case self::TYPE_SUCCESS:
                Html::addCssClass($barOptions,"progress-bar-success");
                break;
        }
        $progressOptions = ['class'=>'progress'];
        switch ($this->theme){
            case self::THEME_STRIPED:
                Html::addCssClass($progressOptions,"progress-striped");
                break;
            case self::THEME_ANIMATED:
                Html::addCssClass($progressOptions,"progress-striped");
                Html::addCssClass($progressOptions,"active");
                break;
            case self::THEME_BASIC:
                break;
        }
        if($this->marginBottom == false)
            Html::addCssStyle($progressOptions,"margin-bottom:0px");

        $text = $this->showText?"$this->value%":"";
        $span = Html::tag("div","$this->value%",['class'=>'sr-only']);
        $bar = Html::tag("div","$span\n$text",$barOptions);
        $progress = Html::tag("div",$bar,$progressOptions);

        echo $progress;
    }
}
?>