<?php
namespace evondu\metronic\widgets;

use evondu\metronic\SummernoteAsset;
use yii\helpers\Html;

/*
use evondu\metronic\widgets\SummernoteEditor
<?= SummernoteEditor::widget([
    //可忽略，自动生成
    'id' => $dataProvider,
    //内嵌的表单元素textarea的name属性
    'name' => $searchModel,
    //初始值
    'value' => "",
    //Summernote的配置
    'options'=>[]
]); ?>
 */
class SummernoteEditor extends MetronicWidget
{
    public $id = "";
    public $name = "";
    public $value = "";
    public $options = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //加载资源
        SummernoteAsset::register($this->view);

        //设置ID
        if(empty($this->id)){
            $this->id = uniqid();
        }

        //默认值
        if(!isset($this->options["height"]))
            $this->options["height"] = 300;
    }

    public function run()
    {
        //summernote
        $options = ["id"=>$this->id];
        $summernote = Html::tag("div",$this->value,$options);

        //textara
        $textaraOptions = ["style"=>"display:none"];
        $textara = empty($this->name)?"":Html::textarea($this->name,$this->value,$textaraOptions);

        //主体
        $body = Html::tag("div","$summernote\n$textara");

        //加载JS
        $this->registerJs();

        //输出
        echo $body;
    }

    public function registerJs(){
        $view = $this->getView();

        //初始化JS
        $view->registerJs(
            "$('#$this->id').summernote(".json_encode($this->options).");"
        );

        //失去焦点时设置值
        $view->registerJs(
            "$('#$this->id').on('summernote.change',function(){
                var textarea = $(this).siblings('textarea');
                var value = $(this).code();
                $(textarea).val(value);
                console.log(value);
            });"
        );
    }
}
?>